l_english:
  train_equipment_1: "Train"

  EQ_MOD_SLOT_locomotive_slot_TITLE: "Locomotive"
  EQ_MOD_CAT_locomotive_type_TITLE: "Locomotives"
  heavy_locomotive: "Heavy Steam Engine"
  heavy_locomotive_desc: "Larger Engines ensure we can haul much longer trains"
  heavy_locomotive_2: "Broad Gauge Diesel Locomotive"
  heavy_locomotive_2_short: "Broad Gauge Diesel"
  heavy_locomotive_2_desc: "With a much wider railway system, we can transport much more in fewer trips.  The primary downsides being it's cost, and fuel."
  heavy_locomotive_3: "Broad Gauge Nuclear Locomotive"
  heavy_locomotive_3_short: "Broad Gauge Nuclear"
  heavy_locomotive_3_desc: "Harnessing Nuclear Energy, our great engines can run much faster and haul much greater at a lower fuel cost."
  
  great_war_locomotive: "Steam Engine"
  great_war_locomotive_desc: "A much older engine that has a much harder time hauling long trains.  perhaps it's time to innovate new transport methods?"
  wartime_locomotive: "Wartime locomotive"
  wartime_locomotive_desc: "An engine that can be mass-produced"
  civilian_locomotive: "Advanced Steam Locomotive"
  civilian_locomotive_short: "Adv. Steam Loc."
  civilian_locomotive_desc: "Faster, Cheaper, and stronger than it's predecessor, this steam engine is a much more stable option for transportation"
  
  civilian_locomotive_2: "Diesel Locomotive"
  civilian_locomotive_2_desc: "Utilizing oil rather than coal, this engine is much more capable of pulling freight"
  
  civilian_locomotive_3: "Nuclear Locomotive"
  civilian_locomotive_3_desc: "Harnessing the power of the atom, our engines can haul much more, and quicker at that.  Just don't mind the cost of upkeep."
  
  
  EQ_MOD_SLOT_fixed_train_type_slot_0_TITLE: "Primary Engine"
  EQ_MOD_SLOT_fixed_train_type_slot_1_TITLE: "Secondary Engine"
  EQ_MOD_SLOT_fixed_train_type_slot_2_TITLE: "Tertiary Engine"
  EQ_MOD_SLOT_fixed_train_type_slot_3_TITLE: "Quaternary Engine"
  EQ_MOD_SLOT_fixed_train_type_slot_4_TITLE: "Quinary Engine"
  EQ_MOD_SLOT_fixed_train_type_slot_5_TITLE: "Senary Engine"
  EQ_MOD_SLOT_fixed_train_type_slot_6_TITLE: "Septenary Engine"
  EQ_MOD_SLOT_vagon9_slot_TITLE: "Ninth Train Car"
  EQ_MOD_SLOT_vagon10_slot_TITLE: "Tenth Train Car"
  EQ_MOD_SLOT_vagon11_slot_TITLE: "Eleventh Train Car"
  EQ_MOD_SLOT_vagon12_slot_TITLE: "twelfth Train Car"
  EQ_MOD_SLOT_vagon13_slot_TITLE: "Thirteenth Train Car"
  EQ_MOD_SLOT_vagon14_slot_TITLE: "Fourteenth Train Car"
  EQ_MOD_SLOT_vagon15_slot_TITLE: "Fifteenth Train Car"
  EQ_MOD_SLOT_vagon16_slot_TITLE: "Sixteenth Train Car"
  EQ_MOD_SLOT_vagon8_slot_TITLE: "Eighth Train Car"
  EQ_MOD_SLOT_vagon7_slot_TITLE: "Seventh Train Car"
  EQ_MOD_SLOT_vagon6_slot_TITLE: "Sixth Train Car"


  GER_great_war_locomotive: "Class 18.4-5"
  GER_wartime_locomotive: "DRB 52 Class"
  SOV_great_war_locomotive: "FD Class"
  SOV_wartime_locomotive: "L Class"
  USA_great_war_locomotive: "Pennsylvania I1s Class"
  USA_wartime_locomotive: "USATC S160 Class"
  JAP_great_war_locomotive: "JNR D50 Class"
  JAP_wartime_locomotive: "JNR D52 Class"
  ENG_great_war_locomotive: "LMS Class 8F"
  ENG_wartime_locomotive: "WD Austerity 2-8-0"
  FRA_great_war_locomotive: "141 B/C SNCF"
  FRA_wartime_locomotive: "141 P SNCF"
  ITA_great_war_locomotive: "FS Class 685"

  EQ_MOD_SLOT_vagon1_slot_TITLE: "First train car"
  EQ_MOD_SLOT_vagon2_slot_TITLE: "Second train car"
  EQ_MOD_SLOT_vagon3_slot_TITLE: "Third train car"
  EQ_MOD_SLOT_vagon4_slot_TITLE: "Fourth train car"
  EQ_MOD_SLOT_vagon5_slot_TITLE: "Fifth train car"
  EQ_MOD_CAT_vagon_type_TITLE: "Freight train cars"
	standart_vagon: "Civilian train car"
	standart_vagon_desc: ""
	armored_vagon: "Armored train car"
	armored_vagon_desc: ""
  EQ_MOD_CAT_aa_vagon_type_TITLE: "Air defense train cars"
  anti_air1_vagon: "Air Defense train car"
  anti_air1_vagon_desc: ""
  anti_air2_vagon: "Improved Air Defense train car"
  anti_air2_vagon_desc: ""
  anti_air3_vagon: "Advanced Air Defense train car"
  anti_air3_vagon_desc: ""


  wartime_train: "War Austerity Train"
  wartime_train_desc: "A simplified design that ommits many features commonly found on regular freight trains for the sake of cheaper production. It is still every bit as vulnerable as a regular train, but can more easily be replaced."
  GER_wartime_train: "DRB 52 Class"
  SOV_wartime_train: "L Class"
  USA_wartime_train: "USATC S160 Class"
  JAP_wartime_train: "JNR D52 Class"
  ENG_wartime_train: "WD Austerity 2-8-0"
  FRA_wartime_train: "141 P SNCF"

  armored_train_desc: "A train engine encased in heavy armor to make it less vulnerable to enemy attack. It can carry as much cargo as any other design, but is more expensive to produce."